### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by nirlipo** [planimation/backend#28]
Currently we do not catch errors messages from the backend. We should give feedback to help animation profile modelers fix the errors while they build the animations.

If you go to: http://editor.planning.domains/#read_session=yiCWKZREGv

Click on Blocksworld_AP.pddl file, and change the parameter of __(predicate on__ from __:parameters (?b ?b2)__ into __:parameters (?b ?b2)__ you get the following uninformative error message. Note that the only error is that ?b1 does not exist within the scope of the predicate.

![image](https://user-images.githubusercontent.com/861782/78754234-82967d80-79ba-11ea-8499-d07fee026384.png)

**Comment by ftdzh1994** [comment]
Hi @nirlipo , 

Sorry I recommit the code because of something wrong git operation. 

What's new is, the error handling for solving visualization phase is enhanced. An example is give below, whose input files are what you mentioned above and parameter changes as well
 ![error_info_1](https://raw.githubusercontent.com/ftdzh1994/hello-world/master/Picture/Screen%20Shot%202020-05-30%20at%207.55.14%20PM.png)

With same PDDL files, other wrong predicate argument input are also tested:
**(equal (?b1 x ) (?b2 x))** -> **(equal (?b1 ) (?b2 x))**       % no property 
output: 
fail to solve the animation file
(?b1, ) used at predicate ON need more arguments

**(equal (?b1 x ) (?b2 x))** -> **(equal (?b1 x) (?b2 ))**      % wrong property
z used in (?b1, z) doesn't exits as a property of ?b1 at predicate ON

What else can be improved ?
1. UI. it refers to frontend so my mates are looking into it;
2. Input which changes **(equal (?b1 x ) (?b2 x))** -> **(equal (?z x) (?b1 x ))** can succeed and get a different animation even though z is not defined in parameters. As it gives no debug info, this kind of error(?) is hard to be caught and handled;
3. Not fully tested with different inputs and files.

Thanks,
Nick

**Comment by nirlipo** [comment]
Thanks Nick! this looks great.

> With same PDDL files, other wrong predicate argument input are also tested:
(equal (?b1 x ) (?b2 x)) -> (equal (?b1 ) (?b2 x)) % no property
output:
fail to solve the animation file
(?b1, ) used at predicate ON need more arguments

I'd output a message like "(?b1, ) used at predicate ON is missing a property"

In terms of more potential errors, have a look at the syntax here:

https://planimation.github.io/documentation/ap_guide/

I'd say that the [visual ](https://planimation.github.io/documentation/ap_guide/#visual) object can trigger some errors when specifying some of its properties, as well as the use of [functions](https://planimation.github.io/documentation/ap_guide/#25-functions)

Take a look at the [worked example](https://planimation.github.io/documentation/ap_guide/#3-worked-example). If you copy and paste the current visuals for blocks, you'll see that it fails. Can you fix the working example and share the error messages? That would be a good test for the current state of the error handling.

For item number 2, that's a great example of non obvious errors that can be caught before running the animation solver. When you do the same change to pickup action in the domain file you get this error message from the online solver:

`undeclared variable ?Z in literal HOLDING. check input files`

Can we do a check that tests if the set of arguments used in the body of the predicate are defined as arguments in the :parameters list?

**Comment by ftdzh1994** [comment]
Hi @nirlipo ,

I'll change the property error message format later,  then do a test and look into other potential problems.

But more information about [worked example ](https://planimation.github.io/documentation/ap_guide/#3-worked-example) are needed as I don't know what problem(or files) this visual block belongs to and can't find any clue on the handover pages.

Now I think, for the non obvious errors(maybe all animation error), it might be systematic and exhaustive  to handle them in parse phase. Because it seems that the error found at solving visualization phase actually originate from an incorrect animation file, which means the solving visualization process won't cause error if the animation correctness is guaranteed.  How do you think of this idea?

**Comment by nirlipo** [comment]
> But more information about worked example are needed as I don't know what problem(or files) this visual block belongs to and can't find any clue on the handover pages.

It's an early version of the animation profile for Blocksworld. [Click in this session](http://editor.planning.domains/#read_session=yiCWKZREGv). For example, you can exchange (copy)  the _visual block_ definition from the worked example, and overwrite (paste) the _visual block_ in the animation profile online.

> Now I think, for the non obvious errors(maybe all animation error), it might be systematic and exhaustive to handle them in parse phase. Because it seems that the error found at solving visualization phase actually originate from an incorrect animation file, which means the solving visualization process won't cause error if the animation correctness is guaranteed. How do you think of this idea?

100% right, these problems can be captured before calling the solver. That would be great! Others like the use of special functions may need the solver to work out the dependencies across several predicates.

**Comment by ftdzh1994** [comment]
Handle the error without debug info:
under the session http://editor.planning.domains/#read_session=yiCWKZREGv :
1. Input which changes (equal (?b1 x ) (?b2 x)) -> (equal (?z x) (?b1 x )) can succeed and get a different animation even though z is not defined in parameters. As it gives no debug info, this kind of error(?) is hard to be caught and handled;

2. if overwrite the visual block definition of this session to the early version of animation profile for Blocksworld(see it in the document), the problem can be solved and but simulated with no picture. This also gives no debug info.
